### ISSUE TITLE
UPDATE some row during SELECT

### ISSUE THREAD

**Issue by dmytro-verbivskyi** [Shmuma/sqlite3-mt4-wrapper#1]
Добрый день, и на том огромное спасибо, за труд!!!
Подскажите сталкивались ли вы с подобной ситуацией, когда в процессе цикла по СЕЛЕКТУ
нужно сделать АПДЕЙТЫ? Сервер возвращает типа код 5: Server is Busy

int cols[3];
string selectPositions = StringConcatenate(
___ "SELECT \* FROM trades ",
___ "WHERE status = 1;");   // only ACTIVE

int handle = sqlite_query(db, selectPositions, cols);

while ( sqlite_next_row(handle) == 1 ) {
___ int dbID        = StrToInteger(sqlite_get_col(handle, 0));
___ int dbTicket    = StrToInteger(sqlite_get_col(handle, 2));
___ double dbOP     = StrToDouble (sqlite_get_col(handle, 3));
___ string updateQuery = "";        

___ if ( OrderSelect(dbTicket, SELECT_BY_POS, MODE_TRADES) ) {

___ } else {    // then it might be closed
_______ Print("it\'s been closed");
_______ updateQuery = StringConcatenate("UPDATE trades SET status = 2 WHERE id = ", dbID, ";");
___ }
___ sqlExec(db, updateQuery);
}
sqlite_free_query(handle);

**Comment by dmytro-verbivskyi** [comment]
Блин, извините, но пришлось хоть так пример исходника выложить.

**Comment by Shmuma** [comment]
Добрый день!

Для примеров исходников на гитхабе есть Gist (https://gist.github.com/), очень удобно.

С такой ситуацией не сталкивался, но судя по коду sqlite, выход только один - в цикле сохранять обновляющие запросы в массиве, которые потом выполнять вне цикла select.

**Comment by dmytro-verbivskyi** [comment]
Спасибо за совет, реализовал этот workaround. Работает приемлемо.
https://gist.github.com/1755439#file_gistfile1.cpp

блин, все равно не выходит вставить исходник прямо сюда в коммент.
